version: "3.8"

services:
  database:
    container_name: saludos-database
    environment:
      - POSTGRES_USER=saludos
      - POSTGRES_PASSWORD=saludos
      - POSTGRES_DB=saludos
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - saludos-database:/var/lib/postgresql/data


  server:
    build:
      context: ./api_saludos
    container_name: api_saludos
    depends_on:
      - database
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://saludos:saludos@saludos-database:5432/saludos
    command: [ "bash", "start.sh" ]
    ports:
      - 5000:5000
    volumes:
      - ./api_saludos:/usr/src/app
    expose:
      - 5000

volumes:
  saludos-database: